# Generated by Django 2.0.2 on 2018-02-18 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='released_date',
            new_name='release_date',
        ),
    ]
